Added validation rules when creating CellOrder record
msenyk/sf-practicum-2024 pull request #34
Opened 2024-12-12 07:48 UTC by Roman45321

Added validation rules:
- "Disallow_populating_Cell_field" - prohibits selecting a cell when the order status is "Pending delivery" or "Delivering", only Parcel Locker.
- "Require_Cell_for_delivered_status" - prohibits the absence of a value in the Cell field when the order status is "Delivered" or "Completed".
- "Ensure_Cell_matches_parcel_locker" - checks if the cell matches the selected Parcel Locker.
- "Lock_fields_after_delivery_completed" - prohibits editing fields other than status, when the order status is "Delivered" or "Completed".

2024-12-12 09:13 UTC, msenyk requested changes

2024-12-12 09:13 UTC, msenyk commented on force-app/main/default/objects/CellOrder__c/fields/Order__c.field-meta.xml
> +    <type>Lookup</type>
It should be Mater-Detail type.

2024-12-12 09:13 UTC, msenyk commented on force-app/main/default/objects/CellOrder__c/validationRules/Lock_fields_after_delivery_completed.validationRule-meta.xml
> +        AND(ISPICKVAL(PRIORVALUE(State__c), &apos;Completed&apos;), ISPICKVAL(State__c, &apos;Completed&apos;))
It is too complicated logic. We can check only prior value equals to "Delivered" and "Completed".

2024-12-18 08:22 UTC, Roman45321 commented
Removed unnecessary validations, changed Order field type to Master-Detail

2024-12-18 20:07 UTC, Roman45321 commented
Resolved conflicts with main branch in Order__c.field-meta.xml

2024-12-23 10:39 UTC, merged